### PR TITLE
Manage dependency by dep

### LINKED ISSUE #14: Dep
in ordet to install dependency

### PR DESCRIPTION
**Pull request by chaspy**
close: https://github.com/chaspy/delete-branch-bot/issues/14

### CODE REVIEW

**Comment by chaspy** [comment]
@kamontia 
please review and merge

**Comment by kamontia** [comment]
@chaspy Should we commit the file under `vendor` directory?

**Comment by chaspy** [comment]
hi @kamontia 
Thank you. Certainly the vendor directory is unnecessary.

**Comment by kamontia** [comment]
@chaspy Thank you for your quick work.

**Pull request merged**
