### PR TITLE
Upload handler.zip to AWS lambda when building

### LINKED ISSUE #25: Upload zip automatically
it can be done using awscli.

```
aws lambda update-function-code \
  --function-name ${FUNCTION_NAME} \
  --zip-file fileb://${FUNCTION_NAME}.zip \
  --region ${AWS_REGION}
```

### PR DESCRIPTION
**Pull request by chaspy**
close: https://github.com/chaspy/delete-branch-bot/issues/25

### CODE REVIEW

**Comment by chaspy** [comment]
@kamontia 

## How to run
I sent .secret you via slack DM.
Please put on this branch, and run `source .secret` and `./build.sh`
You can see the following log.

```
 $ ./build.sh                                                                                                                                                                   ?[aws-lambda-upload]
  adding: delete-branch (deflated 68%)
  adding: private-key.pem (deflated 23%)
{
    "FunctionName": "delete_branch_bot",
    "LastModified": "2018-10-10T13:55:41.497+0000",
    "RevisionId": "56317625-cc7a-4d9e-a74b-1b7d007b3138",
    "MemorySize": 128,
    "Environment": {
        "Variables": {
            "GITHUB_APP_IDENTIFIER": "17630",
            "GITHUB_PRIVATE_KEY": "private-key.pem"
        }
    },
    "Version": "$LATEST",
    "Role": "arn:aws:iam::655123516369:role/service-role/lambda",
    "Timeout": 150,
    "Runtime": "go1.x",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "CodeSha256": "KjfA1n1QyNdmpTkfDJnRZ/ZMdgzX0wDTXms+WsKnxeA=",
    "Description": "",
    "CodeSize": 3536615,
    "FunctionArn": "arn:aws:lambda:ap-northeast-1:655123516369:function:delete_branch_bot",
    "Handler": "delete-branch"
}
```

please review and merge!

ah, and I recommend to use `direnv` to handle secret file 😄

**Comment by kamontia** [comment]
@chaspy  I ran `build.sh` and the log is following as:
```
kamo@kamobookPro: ./build.sh
  adding: delete-branch (deflated 54%)
  adding: private-key.pem (deflated 23%)
{
    "FunctionName": "delete_branch_bot",
    "FunctionArn": "arn:aws:lambda:ap-northeast-1:655123516369:function:delete_branch_bot",
    "Runtime": "go1.x",
    "Role": "arn:aws:iam::655123516369:role/service-role/lambda",
    "Handler": "delete-branch",
    "CodeSize": 5016256,
    "Description": "",
    "Timeout": 150,
    "MemorySize": 128,
    "LastModified": "2018-10-10T14:32:03.856+0000",
    "CodeSha256": "8oTQbkPkmf+1INtaXjHSy7z1SEL7EK6olMcqbv2taec=",
    "Version": "$LATEST",
    "Environment": {
        "Variables": {
            "GITHUB_APP_IDENTIFIER": "17630",
            "GITHUB_PRIVATE_KEY": "private-key.pem"
        }
    },
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "0a365804-d669-4f98-872c-2becc96021a0"
}
./build.sh  2.72s user 0.80s system 60% cpu 5.809 total
```

The my log is a little different from your log. 🤔

**Comment by chaspy** [comment]
wah, I upgraded go version.

from 1.10.3

```
 $ go version
go version go1.11.1 darwin/amd64
```

after that, I got the same result with you 😮 

```
 $ ./build.sh                                                                                                                                                                   ?[aws-lambda-upload]
  adding: delete-branch (deflated 54%)
  adding: private-key.pem (deflated 23%)
{
    "FunctionName": "delete_branch_bot",
    "LastModified": "2018-10-10T15:20:29.057+0000",
    "RevisionId": "b05ca918-8a23-4e92-b10c-f9a1a3ea1a20",
    "MemorySize": 128,
    "Environment": {
        "Variables": {
            "GITHUB_APP_IDENTIFIER": "17630",
            "GITHUB_PRIVATE_KEY": "private-key.pem"
        }
    },
    "Version": "$LATEST",
    "Role": "arn:aws:iam::655123516369:role/service-role/lambda",
    "Timeout": 150,
    "Runtime": "go1.x",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "CodeSha256": "/fbBDVHgpZGA8fF0Sgf13NC/BXSG34jmFZcrCAUZ1hU=",
    "Description": "",
    "CodeSize": 5011916,
    "FunctionArn": "arn:aws:lambda:ap-northeast-1:655123516369:function:delete_branch_bot",
    "Handler": "delete-branch"
}
```

**Comment by kamontia** [comment]
```
kamo@kamobookPro: ./build.sh
  adding: delete-branch (deflated 54%)
  adding: private-key.pem (deflated 23%)
{
    "FunctionName": "delete_branch_bot",
    "FunctionArn": "arn:aws:lambda:ap-northeast-1:655123516369:function:delete_branch_bot",
    "Runtime": "go1.x",
    "Role": "arn:aws:iam::655123516369:role/service-role/lambda",
    "Handler": "delete-branch",
    "CodeSize": 5014147,
    "Description": "",
    "Timeout": 150,
    "MemorySize": 128,
    "LastModified": "2018-10-10T15:22:52.672+0000",
    "CodeSha256": "2H2UljOTUJpVH4xAT528eFF+hQCz5Yr1LPrA5uekWyg=",
    "Version": "$LATEST",
    "Environment": {
        "Variables": {
            "GITHUB_APP_IDENTIFIER": "17630",
            "GITHUB_PRIVATE_KEY": "private-key.pem"
        }
    },
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "e615f281-ff96-447c-ac0c-cd3bc8c82df6"
}
```

Oh, I think it is ready to merge!!!

**Pull request merged**
